export interface District {
  masterDataId: string;
  masterDataName: string;
}

export const districts: District[] = [
  { masterDataId: "1", masterDataName: "Ariyalur" },
  { masterDataId: "2", masterDataName: "Chengalpattu" },
  { masterDataId: "3", masterDataName: "Chennai" },
  { masterDataId: "4", masterDataName: "Coimbatore" },
  { masterDataId: "5", masterDataName: "Cuddalore" },
  { masterDataId: "6", masterDataName: "Dharmapuri" },
  { masterDataId: "7", masterDataName: "Dindigul" },
  { masterDataId: "8", masterDataName: "Erode" },
  { masterDataId: "9", masterDataName: "Kallakurichi" },
  { masterDataId: "10", masterDataName: "Kanchipuram" },
  { masterDataId: "11", masterDataName: "Kanyakumari" },
  { masterDataId: "12", masterDataName: "Karur" },
  { masterDataId: "13", masterDataName: "Krishnagiri" },
  { masterDataId: "14", masterDataName: "Madurai" },
  { masterDataId: "15", masterDataName: "Mayiladuthurai" },
  { masterDataId: "16", masterDataName: "Nagapattinam" },
  { masterDataId: "17", masterDataName: "Namakkal" },
  { masterDataId: "18", masterDataName: "Nilgiris" },
  { masterDataId: "19", masterDataName: "Perambalur" },
  { masterDataId: "20", masterDataName: "Pudukkottai" },
  { masterDataId: "21", masterDataName: "Ramanathapuram" },
  { masterDataId: "22", masterDataName: "Ranipet" },
  { masterDataId: "23", masterDataName: "Salem" },
  { masterDataId: "24", masterDataName: "Sivaganga" },
  { masterDataId: "25", masterDataName: "Tenkasi" },
  { masterDataId: "26", masterDataName: "Thanjavur" },
  { masterDataId: "27", masterDataName: "Theni" },
  { masterDataId: "28", masterDataName: "Thoothukudi" },
  { masterDataId: "29", masterDataName: "Tiruchirappalli" },
  { masterDataId: "30", masterDataName: "Tirunelveli" },
  { masterDataId: "31", masterDataName: "Tirupathur" },
  { masterDataId: "32", masterDataName: "Tiruppur" },
  { masterDataId: "33", masterDataName: "Tiruvallur" },
  { masterDataId: "34", masterDataName: "Tiruvannamalai" },
  { masterDataId: "35", masterDataName: "Tiruvarur" },
  { masterDataId: "36", masterDataName: "Vellore" },
  { masterDataId: "37", masterDataName: "Viluppuram" },
  { masterDataId: "38", masterDataName: "Virudhunagar" },
];